services:
  aprs:
    #build: .
    image: ghcr.io/iu2naf/aprs-docker:main
    container_name: aprs-docker
    restart: unless-stopped
    ports:
      - "14501:14501"
      - "14580:14580"
      - "14581:14581"
